[package]
name = "hcal"
version = "0.1.3"
description = "Hexadecimal calendar"
license = "MIT"
authors = ["0xflotus <0xflotus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4"
