[package]
name = "hcal"
version = "0.1.5"
description = "Hexadecimal calendar for terminal"
license = "MIT"
authors = ["0xflotus"]
edition = "2018"

exclude = ["README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4"
